export const Lookup = {
    "strength": {
      0: "Very much lower strength than",
      1: "Very much lower strength than",
      2: "Very much lower strength than",
      3: "Very much lower strength than",
      4: "Very much lower strength than",
      5: "Very much lower strength than",
      6: "Very much lower strength than",
      7: "Very much lower strength than",
      8: "Very much lower strength than",
      9: "Very much lower strength than",
      10: "Very much lower strength than",
      11: "Very much lower strength than",
      12: "Very much lower strength than",
      13: "Very much lower strength than",
      14: "Very much lower strength than",
      15: "Very much lower strength than",
      16: "Very much lower strength than",
      17: "Very much lower strength than",
      18: "Very much lower strength than",
      19: "Very much lower strength than",
      20: "Very much lower strength than",
      21: "Very much lower strength than",
      22: "Very much lower strength than",
      23: "Very much lower strength than",
      24: "Very much lower strength than",
      25: "Very much lower strength than",
      26: "Very much lower strength than",
      27: "Very much lower strength than",
      28: "Very much lower strength than",
      29: "Very much lower strength than",
      30: "Very much lower strength than",
      31: "Very much lower strength than",
      32: "Very much lower strength than",
      33: "Very much lower strength than",
      34: "Much lower strength than",
      35: "Much lower strength than",
      36: "Much lower strength than",
      37: "Much lower strength than",
      38: "Much lower strength than",
      39: "Much lower strength than",
      40: "Much lower strength than",
      41: "Much lower strength than",
      42: "Much lower strength than",
      43: "Much lower strength than",
      44: "Much lower strength than",
      45: "Much lower strength than",
      46: "Much lower strength than",
      47: "Much lower strength than",
      48: "Much lower strength than",
      49: "Much lower strength than",
      50: "Much lower strength than",
      51: "Much lower strength than",
      52: "Much lower strength than",
      53: "Much lower strength than",
      54: "Much lower strength than",
      55: "Much lower strength than",
      56: "Much lower strength than",
      57: "Much lower strength than",
      58: "Much lower strength than",
      60: "Lower strength than",
      61: "Lower strength than",
      62: "Lower strength than",
      63: "Lower strength than",
      64: "Lower strength than",
      65: "Lower strength than",
      66: "Lower strength than",
      67: "Lower strength than",
      68: "Lower strength than",
      69: "Lower strength than",
      70: "Lower strength than",
      71: "Lower strength than",
      72: "Lower strength than",
      73: "Lower strength than",
      74: "Lower strength than",
      75: "Lower strength than",
      76: "Lower strength than",
      77: "Lower strength than",
      78: "Lower strength than",
      79: "Lower strength than",
      80: "Lower strength than",
      81: "Lower strength than",
      82: "Lower strength than",
      83: "Lower strength than",
      84: "Lower strength than",
      85: "About the same strength as",
      86: "About the same strength as",
      87: "About the same strength as",
      88: "About the same strength as",
      89: "About the same strength as",
      90: "About the same strength as",
      91: "About the same strength as",
      92: "About the same strength as",
      93: "About the same strength as",
      94: "About the same strength as",
      95: "About the same strength as",
      96: "About the same strength as",
      97: "About the same strength as",
      98: "About the same strength as",
      99: "About the same strength as",
      100: "About the same strength as",
      101: "About the same strength as",
      102: "About the same strength as",
      103: "About the same strength as",
      104: "About the same strength as",
      105: "About the same strength as",
      106: "About the same strength as",
      107: "About the same strength as",
      108: "About the same strength as",
      109: "About the same strength as",
      110: "About the same strength as",
      111: "About the same strength as",
      112: "About the same strength as",
      113: "About the same strength as",
      114: "About the same strength as",
      115: "About the same strength as",
      116: "About the same strength as",
      117: "About the same strength as",
      118: "About the same strength as",
      119: "About the same strength as",
      120: "Higher strength than",
      121: "Higher strength than",
      122: "Higher strength than",
      123: "Higher strength than",
      124: "Higher strength than",
      125: "Higher strength than",
      126: "Higher strength than",
      127: "Higher strength than",
      128: "Higher strength than",
      129: "Higher strength than",
      130: "Much higher strength than",
      131: "Much higher strength than",
      132: "Much higher strength than",
      133: "Much higher strength than",
      134: "Much higher strength than",
      135: "Much higher strength than",
      136: "Much higher strength than",
      137: "Much higher strength than",
      138: "Much higher strength than",
      139: "Much higher strength than",
      140: "Much higher strength than",
      141: "Much higher strength than",
      142: "Much higher strength than",
      143: "Much higher strength than",
      144: "Much higher strength than",
      145: "Much higher strength than",
      146: "Much higher strength than",
      147: "Much higher strength than",
      148: "Much higher strength than",
      149: "Much higher strength than",
      150: "Much higher strength than",
      151: "Much higher strength than",
      152: "Much higher strength than",
      153: "Much higher strength than",
      154: "Much higher strength than",
      155: "Much higher strength than",
      156: "Much higher strength than",
      157: "Much higher strength than",
      158: "Much higher strength than",
      159: "Much higher strength than",
      160: "Much higher strength than",
      161: "Much higher strength than",
      162: "Much higher strength than",
      163: "Much higher strength than",
      164: "Much higher strength than",
      165: "Much higher strength than",
      166: "Much higher strength than",
      167: "Much higher strength than",
      168: "Much higher strength than",
      169: "Much higher strength than",
      170: "Much higher strength than",
      171: "Much higher strength than",
      172: "Much higher strength than",
      173: "Much higher strength than",
      174: "Much higher strength than",
      175: "Much higher strength than",
      176: "Much higher strength than",
      177: "Much higher strength than",
      178: "Much higher strength than",
      179: "Much higher strength than",
      180: "Very much higher strength than",
      181: "Very much higher strength than",
      182: "Very much higher strength than",
      183: "Very much higher strength than",
      184: "Very much higher strength than",
      185: "Very much higher strength than",
      186: "Very much higher strength than",
      187: "Very much higher strength than",
      188: "Very much higher strength than",
      189: "Very much higher strength than",
      190: "Very much higher strength than",
      191: "Very much higher strength than",
      192: "Very much higher strength than",
      193: "Very much higher strength than",
      194: "Very much higher strength than",
      195: "Very much higher strength than",
      196: "Very much higher strength than",
      197: "Very much higher strength than",
      198: "Very much higher strength than",
      199: "Very much higher strength than",
      200: "Very much higher strength than",
      201: "Very much higher strength than",
      202: "Very much higher strength than",
      203: "Very much higher strength than",
      204: "Very much higher strength than",
      205: "Very much higher strength than",
      206: "Very much higher strength than",
      207: "Very much higher strength than",
      208: "Very much higher strength than",
      209: "Very much higher strength than",
      210: "Very much higher strength than",
      211: "Very much higher strength than",
      212: "Very much higher strength than",
      213: "Very much higher strength than",
      214: "Very much higher strength than",
      215: "Very much higher strength than",
      216: "Very much higher strength than",
      217: "Very much higher strength than",
      218: "Very much higher strength than",
      219: "Very much higher strength than",
      220: "Very much higher strength than",
      221: "Very much higher strength than",
      222: "Very much higher strength than",
      223: "Very much higher strength than",
      224: "Very much higher strength than",
      225: "Very much higher strength than",
      226: "Very much higher strength than",
      227: "Very much higher strength than",
      228: "Very much higher strength than",
      229: "Very much higher strength than",
      230: "Very much higher strength than",
      231: "Very much higher strength than",
      232: "Very much higher strength than",
      233: "Very much higher strength than",
      234: "Very much higher strength than",
      235: "Very much higher strength than",
      236: "Very much higher strength than",
      237: "Very much higher strength than",
      238: "Very much higher strength than",
      239: "Very much higher strength than",
      240: "Very much higher strength than",
      241: "Very much higher strength than",
      242: "Very much higher strength than",
      243: "Very much higher strength than",
      244: "Very much higher strength than",
      245: "Very much higher strength than",
      246: "Very much higher strength than",
      247: "Very much higher strength than",
      248: "Very much higher strength than",
      249: "Very much higher strength than",
      250: "Very much higher strength than"
    },
    "damage": {
      0: "Much lower damage than",
      1: "Much lower damage than",
      2: "Much lower damage than",
      3: "Much lower damage than",
      4: "Much lower damage than",
      5: "Much lower damage than",
      6: "Much lower damage than",
      7: "Much lower damage than",
      8: "Much lower damage than",
      9: "Much lower damage than",
      10: "Much lower damage than",
      11: "Much lower damage than",
      12: "Much lower damage than",
      13: "Much lower damage than",
      14: "Much lower damage than",
      15: "Lower damage than",
      16: "Lower damage than",
      17: "Lower damage than",
      18: "Lower damage than",
      19: "Lower damage than",
      20: "Lower damage than",
      21: "Lower damage than",
      22: "Lower damage than",
      23: "Lower damage than",
      24: "Lower damage than",
      25: "About the same damage as",
      26: "About the same damage as",
      27: "About the same damage as",
      28: "About the same damage as",
      29: "About the same damage as",
      30: "About the same damage as",
      31: "About the same damage as",
      32: "About the same damage as",
      33: "About the same damage as",
      34: "About the same damage as",
      35: "More damage than",
      36: "More damage than",
      37: "More damage than",
      38: "More damage than",
      39: "More damage than",
      40: "More damage than",
      41: "More damage than",
      42: "More damage than",
      43: "More damage than",
      44: "More damage than",
      45: "More damage than",
      46: "More damage than",
      47: "More damage than",
      48: "More damage than",
      49: "More damage than",
      50: "More damage than",
      51: "More damage than",
      52: "More damage than",
      53: "More damage than",
      54: "More damage than",
      55: "Much more damage than",
      56: "Much more damage than",
      57: "Much more damage than",
      58: "Much more damage than",
      59: "Much more damage than",
      60: "Much more damage than",
      61: "Much more damage than",
      62: "Much more damage than",
      63: "Much more damage than",
      64: "Much more damage than",
      65: "Much more damage than",
      66: "Much more damage than",
      67: "Much more damage than",
      68: "Much more damage than",
      69: "Much more damage than",
      70: "Very much more damage than",
      71: "Very much more damage than",
      72: "Very much more damage than",
      73: "Very much more damage than",
      74: "Very much more damage than",
      75: "Very much more damage than",
      76: "Very much more damage than",
      77: "Very much more damage than",
      78: "Very much more damage than",
      79: "Very much more damage than",
      80: "Very much more damage than",
      81: "Very much more damage than",
      82: "Very much more damage than",
      83: "Very much more damage than",
      84: "Very much more damage than",
      85: "Very much more damage than",
      86: "Very much more damage than",
      87: "Very much more damage than",
      88: "Very much more damage than",
      89: "Very much more damage than",
      90: "Very much more damage than",
      91: "Very much more damage than",
      92: "Very much more damage than",
      93: "Very much more damage than",
      94: "Very much more damage than",
      95: "Very much more damage than",
      96: "Very much more damage than",
      97: "Very much more damage than",
      98: "Very much more damage than",
      99: "Very much more damage than",
      100: "Very much more damage than"
    }
  }