export const Lookup = {
    "strength": {
      0: "very much lower strength than",
      1: "very much lower strength than",
      2: "very much lower strength than",
      3: "very much lower strength than",
      4: "very much lower strength than",
      5: "very much lower strength than",
      6: "very much lower strength than",
      7: "very much lower strength than",
      8: "very much lower strength than",
      9: "very much lower strength than",
      10: "very much lower strength than",
      11: "very much lower strength than",
      12: "very much lower strength than",
      13: "very much lower strength than",
      14: "very much lower strength than",
      15: "very much lower strength than",
      16: "very much lower strength than",
      17: "very much lower strength than",
      18: "very much lower strength than",
      19: "very much lower strength than",
      20: "very much lower strength than",
      21: "very much lower strength than",
      22: "very much lower strength than",
      23: "very much lower strength than",
      24: "very much lower strength than",
      25: "very much lower strength than",
      26: "very much lower strength than",
      27: "very much lower strength than",
      28: "very much lower strength than",
      29: "very much lower strength than",
      30: "very much lower strength than",
      31: "very much lower strength than",
      32: "very much lower strength than",
      33: "very much lower strength than",
      34: "much lower strength than",
      35: "much lower strength than",
      36: "much lower strength than",
      37: "much lower strength than",
      38: "much lower strength than",
      39: "much lower strength than",
      40: "much lower strength than",
      41: "much lower strength than",
      42: "much lower strength than",
      43: "much lower strength than",
      44: "much lower strength than",
      45: "much lower strength than",
      46: "much lower strength than",
      47: "much lower strength than",
      48: "much lower strength than",
      49: "much lower strength than",
      50: "much lower strength than",
      51: "much lower strength than",
      52: "much lower strength than",
      53: "much lower strength than",
      54: "much lower strength than",
      55: "much lower strength than",
      56: "much lower strength than",
      57: "much lower strength than",
      58: "much lower strength than",
      59: "much lower strength than",
      60: "lower strength than",
      61: "lower strength than",
      62: "lower strength than",
      63: "lower strength than",
      64: "lower strength than",
      65: "lower strength than",
      66: "lower strength than",
      67: "lower strength than",
      68: "lower strength than",
      69: "lower strength than",
      70: "lower strength than",
      71: "lower strength than",
      72: "lower strength than",
      73: "lower strength than",
      74: "lower strength than",
      75: "lower strength than",
      76: "lower strength than",
      77: "lower strength than",
      78: "lower strength than",
      79: "lower strength than",
      80: "lower strength than",
      81: "lower strength than",
      82: "lower strength than",
      83: "lower strength than",
      84: "lower strength than",
      85: "about the same strength as",
      86: "about the same strength as",
      87: "about the same strength as",
      88: "about the same strength as",
      89: "about the same strength as",
      90: "about the same strength as",
      91: "about the same strength as",
      92: "about the same strength as",
      93: "about the same strength as",
      94: "about the same strength as",
      95: "about the same strength as",
      96: "about the same strength as",
      97: "about the same strength as",
      98: "about the same strength as",
      99: "about the same strength as",
      100: "about the same strength as",
      101: "about the same strength as",
      102: "about the same strength as",
      103: "about the same strength as",
      104: "about the same strength as",
      105: "about the same strength as",
      106: "about the same strength as",
      107: "about the same strength as",
      108: "about the same strength as",
      109: "about the same strength as",
      110: "about the same strength as",
      111: "about the same strength as",
      112: "about the same strength as",
      113: "about the same strength as",
      114: "about the same strength as",
      115: "about the same strength as",
      116: "about the same strength as",
      117: "about the same strength as",
      118: "about the same strength as",
      119: "about the same strength as",
      120: "higher strength than",
      121: "higher strength than",
      122: "higher strength than",
      123: "higher strength than",
      124: "higher strength than",
      125: "higher strength than",
      126: "higher strength than",
      127: "higher strength than",
      128: "higher strength than",
      129: "higher strength than",
      130: "much higher strength than",
      131: "much higher strength than",
      132: "much higher strength than",
      133: "much higher strength than",
      134: "much higher strength than",
      135: "much higher strength than",
      136: "much higher strength than",
      137: "much higher strength than",
      138: "much higher strength than",
      139: "much higher strength than",
      140: "much higher strength than",
      141: "much higher strength than",
      142: "much higher strength than",
      143: "much higher strength than",
      144: "much higher strength than",
      145: "much higher strength than",
      146: "much higher strength than",
      147: "much higher strength than",
      148: "much higher strength than",
      149: "much higher strength than",
      150: "much higher strength than",
      151: "much higher strength than",
      152: "much higher strength than",
      153: "much higher strength than",
      154: "much higher strength than",
      155: "much higher strength than",
      156: "much higher strength than",
      157: "much higher strength than",
      158: "much higher strength than",
      159: "much higher strength than",
      160: "much higher strength than",
      161: "much higher strength than",
      162: "much higher strength than",
      163: "much higher strength than",
      164: "much higher strength than",
      165: "much higher strength than",
      166: "much higher strength than",
      167: "much higher strength than",
      168: "much higher strength than",
      169: "much higher strength than",
      170: "much higher strength than",
      171: "much higher strength than",
      172: "much higher strength than",
      173: "much higher strength than",
      174: "much higher strength than",
      175: "much higher strength than",
      176: "much higher strength than",
      177: "much higher strength than",
      178: "much higher strength than",
      179: "much higher strength than",
      180: "very much higher strength than",
      181: "very much higher strength than",
      182: "very much higher strength than",
      183: "very much higher strength than",
      184: "very much higher strength than",
      185: "very much higher strength than",
      186: "very much higher strength than",
      187: "very much higher strength than",
      188: "very much higher strength than",
      189: "very much higher strength than",
      190: "very much higher strength than",
      191: "very much higher strength than",
      192: "very much higher strength than",
      193: "very much higher strength than",
      194: "very much higher strength than",
      195: "very much higher strength than",
      196: "very much higher strength than",
      197: "very much higher strength than",
      198: "very much higher strength than",
      199: "very much higher strength than",
      200: "very much higher strength than",
      201: "very much higher strength than",
      202: "very much higher strength than",
      203: "very much higher strength than",
      204: "very much higher strength than",
      205: "very much higher strength than",
      206: "very much higher strength than",
      207: "very much higher strength than",
      208: "very much higher strength than",
      209: "very much higher strength than",
      210: "very much higher strength than",
      211: "very much higher strength than",
      212: "very much higher strength than",
      213: "very much higher strength than",
      214: "very much higher strength than",
      215: "very much higher strength than",
      216: "very much higher strength than",
      217: "very much higher strength than",
      218: "very much higher strength than",
      219: "very much higher strength than",
      220: "very much higher strength than",
      221: "very much higher strength than",
      222: "very much higher strength than",
      223: "very much higher strength than",
      224: "very much higher strength than",
      225: "very much higher strength than",
      226: "very much higher strength than",
      227: "very much higher strength than",
      228: "very much higher strength than",
      229: "very much higher strength than",
      230: "very much higher strength than",
      231: "very much higher strength than",
      232: "very much higher strength than",
      233: "very much higher strength than",
      234: "very much higher strength than",
      235: "very much higher strength than",
      236: "very much higher strength than",
      237: "very much higher strength than",
      238: "very much higher strength than",
      239: "very much higher strength than",
      240: "very much higher strength than",
      241: "very much higher strength than",
      242: "very much higher strength than",
      243: "very much higher strength than",
      244: "very much higher strength than",
      245: "very much higher strength than",
      246: "very much higher strength than",
      247: "very much higher strength than",
      248: "very much higher strength than",
      249: "very much higher strength than",
      250: "very much higher strength than"
    },
    "damage": {
      0: "much lower damage than",
      1: "much lower damage than",
      2: "much lower damage than",
      3: "much lower damage than",
      4: "much lower damage than",
      5: "much lower damage than",
      6: "lower damage than",
      7: "lower damage than",
      8: "lower damage than",
      9: "lower damage than",
      10: "lower damage than",
      11: "about the same damage as",
      12: "about the same damage as",
      13: "about the same damage as",
      14: "about the same damage as",
      15: "about the same damage as",
      16: "about the same damage as",
      17: "about the same damage as",
      18: "about the same damage as",
      19: "about the same damage as",
      20: "about the same damage as",
      21: "more damage than",
      22: "more damage than",
      23: "more damage than",
      24: "more damage than",
      25: "more damage than",
      26: "more damage than",
      27: "more damage than",
      28: "more damage than",
      29: "more damage than",
      30: "more damage than",
      31: "more damage than",
      32: "more damage than",
      33: "more damage than",
      34: "more damage than",
      35: "more damage than",
      36: "more damage than",
      37: "more damage than",
      38: "more damage than",
      39: "more damage than",
      40: "more damage than",
      41: "much more damage than",
      42: "much more damage than",
      43: "much more damage than",
      44: "much more damage than",
      45: "much more damage than",
      46: "much more damage than",
      47: "much more damage than",
      48: "much more damage than",
      49: "much more damage than",
      50: "much more damage than",
      51: "much more damage than",
      52: "much more damage than",
      53: "much more damage than",
      54: "much more damage than",
      55: "much more damage than",
      56: "much more damage than",
      57: "much more damage than",
      58: "much more damage than",
      59: "much more damage than",
      60: "much more damage than",
      61: "much more damage than",
      62: "much more damage than",
      63: "much more damage than",
      64: "much more damage than",
      65: "much more damage than",
      66: "much more damage than",
      67: "much more damage than",
      68: "much more damage than",
      69: "much more damage than",
      70: "much more damage than",
      71: "much more damage than",
      72: "much more damage than",
      73: "much more damage than",
      74: "much more damage than",
      75: "much more damage than",
      76: "much more damage than",
      77: "much more damage than",
      78: "much more damage than",
      79: "much more damage than",
      80: "much more damage than",
      81: "very much more damage than",
      82: "very much more damage than",
      83: "very much more damage than",
      84: "very much more damage than",
      85: "very much more damage than",
      86: "very much more damage than",
      87: "very much more damage than",
      88: "very much more damage than",
      89: "very much more damage than",
      90: "very much more damage than",
      91: "very much more damage than",
      92: "very much more damage than",
      93: "very much more damage than",
      94: "very much more damage than",
      95: "very much more damage than",
      96: "very much more damage than",
      97: "very much more damage than",
      98: "very much more damage than",
      99: "very much more damage than",
      100: "very much more damage than"
    }
  }